//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComputerServiceEntities : DbContext
    {
        public ComputerServiceEntities()
            : base("name=ComputerServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CustomerData> CustomerDatas { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TaskData> TaskDatas { get; set; }
        public DbSet<UserData> UserDatas { get; set; }
    }
}
